ALTER TABLE wts_paper
    MODIFY COLUMN CTIME varchar(16) NOT NULL DEFAULT '',
    MODIFY COLUMN ETIME varchar(16) NOT NULL DEFAULT '',
    MODIFY COLUMN CUSERNAME varchar(64) NOT NULL DEFAULT '',
    MODIFY COLUMN CUSER varchar(32) NOT NULL DEFAULT '',
    MODIFY COLUMN EUSERNAME varchar(64) NOT NULL DEFAULT '',
    MODIFY COLUMN EUSER varchar(32) NOT NULL DEFAULT '',
    MODIFY COLUMN PSTATE varchar(2) NOT NULL DEFAULT '1',
    MODIFY COLUMN SUBJECTNUM int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN POINTNUM int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN COMPLETETNUM int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN AVGPOINT int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN TOPPOINT int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN LOWPOINT int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN ADVICETIME int(11) NOT NULL DEFAULT 60,
    MODIFY COLUMN BOOKNUM int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN UUID varchar(32) NOT NULL DEFAULT '';

ALTER TABLE wts_paper_chapter
    MODIFY COLUMN STYPE varchar(2) NOT NULL DEFAULT '1',
    MODIFY COLUMN PTYPE varchar(2) NOT NULL DEFAULT '2',
    MODIFY COLUMN INITPOINT int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN PARENTID varchar(32) NOT NULL DEFAULT 'NONE',
    MODIFY COLUMN SORT int(11) NOT NULL DEFAULT 1,
    MODIFY COLUMN TREECODE varchar(256) NOT NULL DEFAULT '';

ALTER TABLE wts_subject_type
    MODIFY COLUMN TREECODE varchar(256) NOT NULL DEFAULT '',
    MODIFY COLUMN CTIME varchar(14) NOT NULL DEFAULT '',
    MODIFY COLUMN UTIME varchar(14) NOT NULL DEFAULT '',
    MODIFY COLUMN STATE char(1) NOT NULL DEFAULT '1',
    MODIFY COLUMN CUSER varchar(32) NOT NULL DEFAULT '',
    MODIFY COLUMN MUSER varchar(32) NOT NULL DEFAULT '',
    MODIFY COLUMN READPOP char(1) NOT NULL DEFAULT '1',
    MODIFY COLUMN WRITEPOP char(1) NOT NULL DEFAULT '1';

ALTER TABLE wts_random_item
    MODIFY COLUMN CTIME varchar(16) NOT NULL DEFAULT '',
    MODIFY COLUMN CUSER varchar(32) NOT NULL DEFAULT '',
    MODIFY COLUMN PSTATE varchar(2) NOT NULL DEFAULT '1';

ALTER TABLE wts_random_step
    MODIFY COLUMN TIPTYPE varchar(2) NOT NULL DEFAULT '2',
    MODIFY COLUMN SUBNUM int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN SUBPOINT int(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN SORT int(11) NOT NULL DEFAULT 1;

ALTER TABLE wts_subject_version
    MODIFY COLUMN CTIME varchar(16) NOT NULL DEFAULT '',
    MODIFY COLUMN CUSERNAME varchar(64) NOT NULL DEFAULT '',
    MODIFY COLUMN CUSER varchar(32) NOT NULL DEFAULT '',
    MODIFY COLUMN PSTATE varchar(2) NOT NULL DEFAULT '1',
    MODIFY COLUMN TIPSTR varchar(256) NOT NULL DEFAULT '',
    MODIFY COLUMN TIPTYPE varchar(2) NOT NULL DEFAULT '2',
    MODIFY COLUMN SUBJECTID varchar(32) NOT NULL DEFAULT '';

ALTER TABLE wts_subject_answer
    MODIFY COLUMN CTIME varchar(16) NOT NULL DEFAULT '',
    MODIFY COLUMN CUSERNAME varchar(64) NOT NULL DEFAULT '',
    MODIFY COLUMN CUSER varchar(32) NOT NULL DEFAULT '',
    MODIFY COLUMN PSTATE varchar(2) NOT NULL DEFAULT '1',
    MODIFY COLUMN VERSIONID varchar(32) NOT NULL DEFAULT '',
    MODIFY COLUMN ANSWER varchar(512) NOT NULL DEFAULT '',
    MODIFY COLUMN SORT int(11) NOT NULL DEFAULT 1,
    MODIFY COLUMN RIGHTANSWER varchar(2) NOT NULL DEFAULT '0',
    MODIFY COLUMN UUID varchar(32) NOT NULL DEFAULT '';
